[package]
name = "template"
version = "0.0.1"
entrypoint = "src/lib.typ"
authors = [
  "Clemens Koza <https://github.com/SillyFreak/>"
]
license = "MIT"
description = "template package"
repository = "https://github.com/SillyFreak/typst-packages/tree/main/template"
keywords = []
# compiler = ""
exclude = [
  # docs and gallery are not needed in the final package
  "docs/*",
  "gallery/*",
]
